<?php
/**
 * VCD-db - a web based VCD/DVD Catalog system
 * Copyright (C) 2003-2007 Konni - konni.com
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 * 
 * @author  Hákon Birgisson <konni@konni.com>
 * @package Kernel
 * @version $Id: VCDPageFileHander.php 1066 2007-08-15 17:05:56Z konni $
 * @since 0.90
 */
?>
<?php

/**
 * All images, NFO's and other downloadeble contents will be routed through this controller.
 *
 */
class VCDPageFileHandler extends VCDBasePage {
	
	
	public function __construct(_VCDPageNode $node) {
		parent::__construct($node);

		
		if ((!is_null($this->getParam('cover_id')) && (is_numeric($this->getParam('cover_id'))))) {
			$this->doImage($this->getParam('cover_id'));
		} elseif ((!is_null($this->getParam('nfo')) && (is_numeric($this->getParam('nfo'))))) {
			$this->doNfo($this->getParam('nfo'));
		} elseif (strcmp($this->getParam('action'),'data')==0) {
			$this->doExport();
		}
		
		
		// We never use the parent functions ..
		exit();
	}
	
	
	/**
	 * Export data
	 *
	 */
	private function doExport() {

		$type = $this->getParam('t');
		$filter = $this->getParam('f');
		$compression = $this->getParam('c');
		
		switch ($type) {
			case 'xml':
				$this->exportXml($filter,$compression);
				break;
			
			case 'xls':
				$this->exportXls();
				break;
				
			case 'pdf':
				$this->exportPdf();
				break;
		
			default:
				break;
		}
	}
	
	
	/**
	 * Export VCD-db movie data as XML files, optionally compressed
	 *
	 * @param string $filter | Use only subset of the data?
	 * @param string $compression | Which compression to use? 
	 */
	private function exportXml($filter=null, $compression=null) {
		
		if (!is_null($filter) && strcmp($filter,'thumbs')==0) {
			
			switch ($compression) {
				case 'tar':
					VCDXMLExporter::exportThumbnails(VCDXMLExporter::EXP_TGZ);
					break;
			
				case 'zip':
					VCDXMLExporter::exportThumbnails(VCDXMLExporter::EXP_ZIP);
					break;
					
				default:
					VCDXMLExporter::exportThumbnails(VCDXMLExporter::EXP_XML);
					break;
			}
			
		} else {
			
			switch ($compression) {
				case 'tar':
					VCDXMLExporter::exportMovies(VCDXMLExporter::EXP_TGZ);
					break;
			
				case 'zip':
					VCDXMLExporter::exportMovies(VCDXMLExporter::EXP_ZIP);
					break;
					
				default:
				VCDXMLExporter::exportMovies(VCDXMLExporter::EXP_XML);
					break;
			}
		}
	}
	
	/**
	 * Export the movie list as Excel document
	 *
	 */
	private function exportXls() {
		
		// include the Excel lib
		require_once(VCDDB_BASE.'/classes/external/excel/ExcelGen.php');
		
		$arrMovies = MovieServices::getAllVcdByUserId(VCDUtils::getUserID());
	
		//initiate a instance of "excelgen" class
		$excel = new ExcelGen("My_Movies");
	
		//initiate $row,$col variables
		$row=0;
		$col=0;
	
		//write text in cell(0,0)
		$excel->WriteText($row,$col, utf8_decode( VCDLanguage::translate('menu.movies') ) . " " . "(".date("d.m.Y").") (Generated by VCD-db)");
		$row++;
	
		// Write the column headers
		$excel->WriteText($row, 0, utf8_decode( VCDLanguage::translate('movie.title')) );
		$excel->WriteText($row, 1, utf8_decode( VCDLanguage::translate('movie.category')) );
		$excel->WriteText($row, 2, utf8_decode( VCDLanguage::translate('movie.media')) );
		$excel->WriteText($row, 3, utf8_decode( VCDLanguage::translate('movie.year')) );
		$excel->WriteText($row, 4, utf8_decode( VCDLanguage::translate('movie.mediaindex')) );
		$row++;
	
		for ($row; $row < sizeof($arrMovies) + 2; $row++) {
			$col = 0;
	
			$movie = $arrMovies[$row-2];
	
			// Write The title
			$excel->WriteText($row, $col, $movie->getTitle());
			$col++;
	
			// Write The category
			if (!is_null($movie->getCategory())) {
				$excel->WriteText($row, $col, utf8_decode($movie->getCategory()->getName(true)));
			}
			$col++;
	
			// Write The Media type
			if (!is_null($movie->getMediaType())) {
				$mediaTypeObj = $movie->getMediaType();
				$excel->WriteText($row, $col, $mediaTypeObj[0]->getDetailedName());
			}
			$col++;
	
			// Write The Year
			$excel->WriteNumber($row, $col, $movie->getYear());
			$col++;
	
			// Write The Media index
			$arr = SettingsServices::getMetadata($movie->getID(), VCDUtils::getUserID(), 'mediaindex');
			if (is_array($arr) && sizeof($arr) == 1) {
				$excel->WriteText($row, $col, $arr[0]->getMetadataValue());
			}
			$col++;
		}
	
		//stream Excel for user to download or show on browser
		$excel->SendFile();
		exit();
	}
	
	
	/**
	 * Export the movie list as PDF
	 *
	 */
	private function exportPdf() {
		
		// Include the PDF lib ...
		require_once(VCDDB_BASE.'/classes/external/pdf/tcpdf.php');
				
		
		$arrMovies = MovieServices::getAllVcdByUserId(VCDUtils::getUserID());
		$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true);
		
		$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
		$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
		$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
	
		$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
		$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
	
		$pdf->AliasNbPages();
		$pdf->SetFont("FreeSerif", "", 10);
		$pdf->AddPage();
		
		$row=0;
		
		$pdf->Cell(0,5, VCDLanguage::translate('menu.movies') . " " . "(".date("d.m.Y").") (Generated by VCD-db)",1,1);
		$row++;
		
		$pdf->Cell(82,5, VCDLanguage::translate('movie.title'),1,0);
		$pdf->Cell(27,5, VCDLanguage::translate('movie.category'),1,0);
		$pdf->Cell(27,5, VCDLanguage::translate('movie.media'),1,0);
		$pdf->Cell(27,5, VCDLanguage::translate('movie.year'),1,0);
		$pdf->Cell(27,5, VCDLanguage::translate('movie.mediaindex'),1,1);
		$row++;
		
		
		for ($row; $row < sizeof($arrMovies) + 2; $row++) {
			
			$movie = $arrMovies[$row-2];
			
			if (strlen($movie->getTitle())<=56){
			$pdf->Cell(82,5,$movie->getTitle(),1,0);
			}
			elseif (strlen($movie->getTitle())>56){
			$pdf->Cell(82,5,substr_replace($movie->getTitle(),'...',52),1,0);
			}
			
		if (!is_null($movie->getCategory())) {
			$pdf->Cell(27,5,$movie->getCategory()->getName(true),1,0);
			}
				
		if (!is_null($movie->getMediaType())) {
			$mediaTypeObj = $movie->getMediaType();
			$pdf->Cell(27,5,$mediaTypeObj[0]->getDetailedName(),1,0);
			}
			
			$pdf->Cell(27,5,$movie->getYear(),1,0);
			
		$arr = SettingsServices::getMetadata($movie->getID(), VCDUtils::getUserID(), 'mediaindex');
		if (is_array($arr) && sizeof($arr) == 1) {
			$pdf->Cell(27,5,$arr[0]->getMetadataValue(),1,1);
			}
		else
			$pdf->Cell(27,5,'',1,1);
		}
	
		$pdf->Output('MyMovies.pdf','D');
		exit();
	}
	
		
	private function doFile() {
		
	}
	
	/**
	 * Show NFO file in browser
	 *
	 */
	private function doNfo($metadata_id) {
		
		$metaObj = SettingsServices::getMetadataById($metadata_id);
		if (!$metaObj instanceof metadataObj ) {
			return;
		}
		
		$nfoFilePath = VCDDB_BASE.DIRECTORY_SEPARATOR.NFO_PATH.$metaObj->getMetadataValue();
		$nfoFontPath = VCDDB_BASE.DIRECTORY_SEPARATOR.'includes/fonts/terminal.phpfont';
		
		
		if (file_exists($nfoFilePath)) {
			
			$filesize =	filesize ($nfoFilePath);
			$filenum = fopen ($nfoFilePath, "r");
			$nfoFile = fread ($filenum, $filesize);
			fclose ($filenum);	
			
			if (!file_exists ( $nfoFontPath ) ) {
				throw new VCDProgramException('The fontfile was not found.');
			}
			
			
			// Create the image
			$nfolines = explode ("\n", $nfoFile);
			$font = imageloadfont ($nfoFontPath);
	
			$width = 0;
			$height = 0;
			$fontwidth 	= ImageFontWidth ($font);
			$fontheight = ImageFontHeight ($font);
	
			foreach ( $nfolines as $line ) {
				if ( (strlen ($line)*$fontwidth) > $width ) {
					$width = strlen ($line) * $fontwidth;
				}
				$height += $fontheight;
			}
	
			$width += $fontwidth*2;
			$height += $fontheight*3;
	
			$image = ImageCreate ($width, $height);
	
			$white = ImageColorAllocate ($image, 255,255,255);
			imagecolortransparent ($image, $white);
	
			$black = ImageColorAllocate ($image, 0, 0, 0);
	
			$i = $fontheight;
			foreach ( $nfolines as $line ) {
				ImageString ($image, $font , $fontwidth, $i, $line, $black);
				$i += $fontheight;
			}
	
			$poweredby = "powered by VCD-db (c) vcddb.konni.com";
			$wid = ($width - ($fontwidth*strlen($poweredby) ) ) / 2;
			ImageString ($image, $font , $wid, $i, $poweredby, $black);
	
			ImageAlphaBlending($image, true);
			
			Header("Content-type: image/png"); 
			header('Content-Disposition: inline; filename="'.$metaObj->getMetadataValue().'.png"');
			header("Content-Transfer-Encoding: binary\n");
			ImagePNG ($image);   
			ImageDestroy($image);
			exit();
			
			
		} 
		
	}
	
	/**
	 * Show cover image in the browser
	 *
	 * @param string $cover_id | The id of the cover to display
	 */
	private function doImage($cover_id) {
		
		$cover = CoverServices::getCoverById($cover_id);
		
		if ($cover instanceof cdcoverObj ) {
			if ($cover->isInDB()) {
				
				$imageClass = new VCDImage($cover->getImageID());
				
				@session_write_close();
				@ob_end_clean();
				header("Cache-Control: ");
				header("Pragma: ");
				header("Content-Type: application/octet-stream");
				header("Content-Length: " .(string)($imageClass->getFilesize()) );
				header('Content-Disposition: attachment; filename="'.$imageClass->getImageName().'"');
				header("Content-Transfer-Encoding: binary\n");
				echo $imageClass->getImageStream($cover->getImageID());
								
				
			} else {
				
				if (strcmp(strtolower($cover->getCoverTypeName()),'thumbnail')==0) {
					$fullpath = VCDDB_BASE.DIRECTORY_SEPARATOR.THUMBNAIL_PATH.$cover->getFilename();
				} else {
					$fullpath = VCDDB_BASE.DIRECTORY_SEPARATOR.COVER_PATH.$cover->getFilename();
				}
				$this->streamFile($fullpath);
				
			}
			
		}
		exit();
	}
	
	/**
	 * Stream binary data to browser
	 *
	 */
	private function doStream() {
		
	}
	
	
	/**
	 * Stream the contents of the file to browser
	 *
	 * @param string $path | The full path to the file
	 * @return bool | Returns true on success
	 */
	private function streamFile($path) {
		session_write_close();
		@ob_end_clean();
		if (!is_file($path) || connection_status()!=0) {
			return(false);
		}
		
		//to prevent long file from getting cut off from    //max_execution_time
		set_time_limit(0);
		
		$name = basename($path);
		
		//filenames in IE containing dots will screw up the
		//filename unless we add this
		
		if (strstr($_SERVER['HTTP_USER_AGENT'], "MSIE")) {
			$name = preg_replace('/\./', '%2e', $name, substr_count($name, '.') - 1);			
		}

		
		//required, or it might try to send the serving    //document instead of the file
		header("Cache-Control: ");
		header("Pragma: ");
		header("Content-Type: application/octet-stream");
		header("Content-Length: " .(string)(filesize($path)) );
		header('Content-Disposition: attachment; filename="'.$name.'"');
		header("Content-Transfer-Encoding: binary\n");
		
		if($file = fopen($path, 'rb')){
			while( (!feof($file)) && (connection_status()==0) ){
				print(fread($file, 1024*8));
				flush();
			}
			fclose($file);
		}
		
		return((connection_status()==0) && !connection_aborted());
		
		}
	
}