<?xml version='1.0' encoding='UTF-8'?>

<definitions name="http://vcddb.konni.com" targetNamespace="urn:http://vcddb.konni.com" xmlns:typens="urn:http://vcddb.konni.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
	<message name="authenticate">
		<part name="username" type="xsd:string"/>
		<part name="password" type="xsd:string"/>
	</message>
	<message name="authenticateResponse">
		<part name="authenticateReturn" type="xsd:boolean"/>
	</message>
	<portType name="SoapAuthenticationServicePortType">
		<operation name="authenticate">
			<documentation>
				Authenticate user via webservice call
			</documentation>
			<input message="typens:authenticate"/>
			<output message="typens:authenticateResponse"/>
		</operation>
	</portType>
	<binding name="SoapAuthenticationServiceBinding" type="typens:SoapAuthenticationServicePortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="authenticate">
			<soap:operation soapAction="urn:SoapAuthenticationServiceAction"/>
			<input>
				<soap:body namespace="urn:http://vcddb.konni.com" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body namespace="urn:http://vcddb.konni.com" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="AuthenticationService">
		<port name="SoapAuthenticationServicePort" binding="typens:SoapAuthenticationServiceBinding">
			<soap:address location="http://tempuri"/>
		</port>
	</service>
</definitions>
